util.AddNetworkString("allyChangedHero")
util.AddNetworkString("abilityCastRequest")
util.AddNetworkString("abilityCastSuccess")
util.AddNetworkString("openPermissionsMenu")
util.AddNetworkString("ultimateCastRequest")
util.AddNetworkString("adminConVarChanged")